export const GAME_CONFIG = {
  groundY: 93,
  gravity: 0.6,
  jumpVelocity: 11.95,
  playerX: 80,
  playerW: 24,
  playerH: 36,
  playerHitboxH: 32,
  playerHitboxBottomOffset: 10,
  hitboxPadding: 0,
  spawnGapPxMin: 260,
  spawnGapPxMax: 600,
  obstacleWMin: 14,
  obstacleWMax: 40,
  obstacleHMin: 20,
  obstacleHMax: 85,
  baseMovePx: 6,
  speedStart: 1,
  speedMax: 5,
  distancePerSecond: 9.22,
} as const
